### ISSUE TITLE
Create intro

### ISSUE THREAD

**Issue by HelenaLisenok** [HelenaLisenok/Homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by PawelPavlovich** [comment]
I am so happy to help you to make this work.

**Comment by PawelPavlovich** [comment]
Hello. My name is Donald John Trump. I was born June 14, 1946. I am an American media personality and businessman who served as the 45th president of the United States from 2017 to 2021.

**Comment by PawelPavlovich** [comment]
Hello. My name is Donald John Trump. I was born June 14, 1946. I am an American media personality and businessman who served as the 45th president of the United States from 2017 to 2021.

**Comment by PawelPavlovich** [comment]
Hello. My name is Donald John Trump. I was born June 14, 1946. I am an American media personality and businessman who served as the 45th president of the United States from 2017 to 2021.

And I am really happy to serve my country

**Comment by HelenaLisenok** [comment]
Well done
