### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by HelenaLisenok** [HelenaLisenok/Homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by PawelPavlovich** [comment]
https://twitter.com/donaldtrump
https://twitter.com/ivankatrump

**Comment by PawelPavlovich** [comment]
https://www.instagram.com/realdonaldtrump/?hl=ru
https://twitter.com/donaldtrump
https://twitter.com/ivankatrump
